/*
 * KillRing.java
 *
 * Copyright (C) 1998-2002 Peter Graves
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

package org.armedbear.j;

import java.awt.HeadlessException;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.ClipboardOwner;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;

public final class KillRing extends Ring implements ClipboardOwner {
    private ClipboardOwner clipboardOwner; // Either this or null.

    /** In place of the system's, for a j with no display: tests. */
    private static Clipboard clipboardInstead;
    private static Clipboard selectionInstead;

    public KillRing() {
        super(30);
    }

    public void copyLastKillToSystemClipboard() {
        String kill = pop();
        if (kill != null)
            setClipboardContents(kill);
    }

    public void promoteLastPaste() {
        promoteLast();
        // Don't change the contents of the system clipboard unless we are the
        // clipboard owner!
        if (clipboardOwner == this)
            setClipboardContents(peek());
    }

    /**
     * What paste does first: text another program put on the system
     * clipboard becomes the newest kill, so that it is what is pasted.
     */
    public void takeClipboard() {
        final String text = getText(systemClipboard());
        if (text != null && text.length() > 0)
            appendNew(text);
    }

    private void setClipboardContents(String s) {
        if (setText(systemClipboard(), s, this))
            clipboardOwner = this;
    }

    public void lostOwnership(Clipboard clipboard, Transferable contents) {
        clipboardOwner = null;
    }

    /**
     * Uses these clipboards in place of the system clipboard and the primary
     * selection, as a j with no display has neither; null goes back to the
     * system's.
     */
    public static void useClipboards(Clipboard clipboard, Clipboard selection) {
        clipboardInstead = clipboard;
        selectionInstead = selection;
    }

    /** The system clipboard, or null where there is none. */
    public static Clipboard systemClipboard() {
        if (clipboardInstead != null)
            return clipboardInstead;
        try {
            return Toolkit.getDefaultToolkit().getSystemClipboard();
        }
        catch (HeadlessException e) {
            return null;
        }
    }

    /** The primary selection, as X has it, or null where there is none. */
    public static Clipboard systemSelection() {
        if (selectionInstead != null)
            return selectionInstead;
        try {
            return Toolkit.getDefaultToolkit().getSystemSelection();
        }
        catch (HeadlessException e) {
            return null;
        }
    }

    /** The text on a clipboard, or null for none. */
    public static String getText(Clipboard clipboard) {
        if (clipboard == null)
            return null;
        try {
            final Transferable t = clipboard.getContents(null);
            if (t != null)
                return (String) t.getTransferData(DataFlavor.stringFlavor);
        }
        catch (Exception e) {
            // Not text, or not now.
        }
        return null;
    }

    /** Puts text on a clipboard; false where it could not be done. */
    public static boolean setText(
        Clipboard clipboard,
        String s,
        ClipboardOwner owner
    ) {
        if (clipboard == null || s == null)
            return false;
        // Work around Java bug 4213197. Make sure the string we put on the
        // system clipboard was not generated by a substring operation.
        final StringSelection ss = new StringSelection(new String(s));
        try {
            clipboard.setContents(ss, owner);
            return true;
        }
        catch (IllegalStateException e) {
            Log.debug(e);
            return false;
        }
    }
}
